package io.src.model.Enums;

public enum AnimationKey {
    WALK_UP,  WALK_DOWN,  WALK_LEFT,  WALK_RIGHT,
    IDLE_UP,  IDLE_DOWN,  IDLE_LEFT,  IDLE_RIGHT,
    AXE_SWING_UP,  AXE_SWING_DOWN,  AXE_SWING_LEFT,  AXE_SWING_RIGHT,
    HOE_SWING_UP,  HOE_SWING_DOWN,  HOE_SWING_LEFT,  HOE_SWING_RIGHT,
    PICKAXE_SWING_UP,  PICKAXE_SWING_DOWN,  PICKAXE_SWING_LEFT,  PICKAXE_SWING_RIGHT,
    WATERINGCAN_SWING_UP,  WATERINGCAN_SWING_DOWN,  WATERINGCAN_SWING_LEFT,  WATERINGCAN_SWING_RIGHT
}
    // اگر لازم دارید: RUN_… یا ATTACK_…WATERINGCAN
