package io.src.model.Enums;

public enum AnimationKey {
    WALK_UP,  WALK_DOWN,  WALK_LEFT,  WALK_RIGHT,
    IDLE_UP,  IDLE_DOWN,  IDLE_LEFT,  IDLE_RIGHT, FAINTED,
    AXE_SWING_UP,  AXE_SWING_DOWN,  AXE_SWING_LEFT,  AXE_SWING_RIGHT,
    HOE_SWING_UP,  HOE_SWING_DOWN,  HOE_SWING_LEFT,  HOE_SWING_RIGHT,
    PICKAXE_SWING_UP,  PICKAXE_SWING_DOWN,  PICKAXE_SWING_LEFT,  PICKAXE_SWING_RIGHT,
    WATERINGCAN_SWING_UP,  WATERINGCAN_SWING_DOWN,  WATERINGCAN_SWING_LEFT,  WATERINGCAN_SWING_RIGHT,
    SCYTHE_SWING_UP, SCYTHE_SWING_DOWN,  SCYTHE_SWING_LEFT,  SCYTHE_SWING_RIGHT,
    FISHINGPOLE_SWING_UP, FISHINGPOLE_SWING_DOWN , FISHINGPOLE_SWING_LEFT , FISHINGPOLE_SWING_RIGHT,
    MILKPAIL_SWING_UP, MILKPAIL_SWING_DOWN, MILKPAIL_SWING_LEFT, MILKPAIL_SWING_RIGHT
}
